### ISSUE TITLE
Game crash when putting a ground block in Timeswap Table

### ISSUE THREAD

**Issue by Maxbrick** [DawnTeamMC/Mubble#69]
When i put in a ground block in the Timeswap Table, a game crash occurs:

The game crashed whilst rendering screen
Error: java.lang.IndexOutOfBoundsException: Index: 204, Size: 45
Exit Code: -1

(Mod Version: 4.0 pre-3)

Im guessing that maybe the new update somehow made a limitation to the number of items displayed on the time table, because if you put any ground block, it shows all the ground blocks in the table. I'm not sure though, this didnt happen in the older version..

1. Pick any ground block
2. Put it in the Timeswap Table
3. The game will freeze, and crash

Expected behavior
The timeswap table would function normally without crashing

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version. I was so dumb that I used the wrong variable to get tooltips and yeah whatever
