### ISSUE TITLE
Brick Block Makes No Sound

### ISSUE THREAD

**Issue by Maxbrick** [DawnTeamMC/Mubble#70]
When I bonk a brick block with my head, and it doesnt make a power-up, it breaks without making a sound. However, it still plays it when I break it with any other method.

Guess I'm just not Mario.

1. Get any Mario brick block
2. Place the brick block, jump below it 
3. It should make no sound if it breaks.
4. If it didn't happen, then its possible it happened after I installed worldedit

Expected Behavior:
Brick block breaks and plays the brick block sound.

**Comment by Hugman76** [comment]
This also affects:
- Rotating Blocks
- Unstable Stone
- Placer

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
