### ISSUE TITLE
Crash when starting game

### ISSUE THREAD

**Issue by The-Fireplace** [DawnTeamMC/Mubble#71]
**Describe the bug**
The game crashes when it starts.
1.16.3 crash report (with other mods)
https://paste.ubuntu.com/p/Z5pdTJvMSf/
1.16.2 crash report (just Mubble, Dawn API, and Fabric API)
https://paste.ubuntu.com/p/Rm3gQzfSPV/

**To Reproduce**
1. Install Mubble 4.0-pre3 on Minecraft 1.16.2 or 1.16.3
2. Start the game

**Expected behavior**
The game starts without crashing.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
